[package]
name = "cmaker"
version = "0.1.0"
authors = ["schrodingerzhu <i@zhuyi.fan>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.2.0"
regex = "1.3.1"
cpp_demangle = "0.2.14"
path-dedot = "1.1.13"